export const RU_LOCALE = {
  UNKNOWN: "Неизвестно",
  MEMBER_PLURAL: "участники",
  MEMBER_SINGULAR: "участник",
  NO_TEAMS_FOUND: "Команды не найдены",
  MANAGE_TEAM_MEMBERS_DESCRIPTION: "Поиск и добавление участников организации в эту команду.",
  MANAGE_TEAM_MEMBERS: "Управление участниками команды",
  UPDATE_TEAM_SUCCESS: "Команда успешно обновлена",
  ADD_TEAM_MEMBER_SUCCESS: "Участник успешно добавлен в команду",
  REMOVE_TEAM_MEMBER_SUCCESS: "Участник успешно удален из команды",
  REMOVE_TEAM_MEMBER_CONFIRM: "Вы уверены, что хотите удалить этого участника из команды?",
  REMOVE_TEAM_MEMBER: "Удалить участника команды",
  ADD_TEAM_MEMBER: "Добавить участника команды",
  TEAM_MEMBERS_DESCRIPTION: "Управление участниками вашей команды и их ролями.",
  TEAM_MEMBERS: "Участники команды",
  TEAM_NAME_DOES_NOT_MATCH: "Имя команды не совпадает",
  TEAM_NAME_REQUIRED: "Имя команды обязательно",
  DELETE_TEAM_INSTRUCTIONS: "Введите имя команды, чтобы продолжить:",
  DELETE_TEAM_SUCCESS: "Команда успешно удалена",
  DELETE_TEAM_DESCRIPTION: "Навсегда удалить эту команду и все ее содержимое.",
  DELETE_TEAM: "Удалить команду",
  USER_TEAMS_DESCRIPTION: "Вы являетесь участником следующих команд.",
  TEAMS_DESCRIPTION: "Управление вашими командами внутри вашей организации.",
  TEAM_NAME_INSTRUCTIONS: "Пожалуйста, используйте максимум 64 символа.",
  TEAM_NAME_DESCRIPTION: "Это видимое имя вашей команды.",
  TEAM_NAME_PLACEHOLDER: "Инженерная команда",
  TEAM_NAME: "Имя команды",
  CREATE_TEAM_INSTRUCTIONS: "Добавить новую команду в вашу организацию.",
  REMOVE_TEAM_CONFIRM: "Вы уверены, что хотите удалить эту команду из организации?",
  UPDATE_TEAMS_DESCRIPTION: "Добавить или удалить команды для этого участника",
  UPDATE_TEAM_DESCRIPTION: "Обновить имя этой команды",
  REMOVE: "Удалить",
  ADD: "Добавить",
  SELECT_TEAMS: "Выбрать команды",
  UPDATE_TEAMS: "Обновить команды",
  UPDATE_TEAM: "Обновить команду",
  CREATE_TEAM_SUCCESS: "Команда успешно создана",
  CREATE_TEAM: "Создать команду",
  TEAM_SET_ACTIVE: "Сделать активной",
  TEAM_ACTIVE: "Активна",
  TEAMS: "Команды",
  TEAM: "Команда",
  SLUG_DOES_NOT_MATCH: "Слаг (URL) не совпадает",
  SLUG_REQUIRED: "Слаг (URL) организации обязателен",
  DELETE_ORGANIZATION_INSTRUCTIONS: "Введите слаг (URL) организации, чтобы продолжить:",
  DELETE_ORGANIZATION_SUCCESS: "Организация успешно удалена",
  DELETE_ORGANIZATION_DESCRIPTION:
    "Навсегда удалить вашу организацию и все ее содержимое. Это действие необратимо — пожалуйста, продолжайте с осторожностью.",
  DELETE_ORGANIZATION: "Удалить организацию",
  INVITATION_EXPIRED: "Срок действия этого приглашения истек",
  REJECT: "Отклонить",
  ACCEPT: "Принять",
  INVITATION_REJECTED: "Приглашение успешно отклонено",
  INVITATION_ACCEPTED: "Приглашение успешно принято",
  ACCEPT_INVITATION_DESCRIPTION: "Вас пригласили присоединиться к организации.",
  ACCEPT_INVITATION: "Принять приглашение",
  INVITATION_CANCELLED: "Приглашение успешно отменено",
  CANCEL_INVITATION: "Отменить приглашение",
  PENDING_USER_INVITATIONS_DESCRIPTION: "Приглашения, которые вы получили от организаций.",
  PENDING_INVITATIONS_DESCRIPTION: "Управление ожидающими приглашениями в вашу организацию.",
  PENDING_INVITATIONS: "Ожидающие приглашения",
  SEND_INVITATION_SUCCESS: "Приглашение успешно отправлено",
  SEND_INVITATION: "Отправить приглашение",
  MEMBER_ROLE_UPDATED: "Роль участника успешно обновлена",
  UPDATE_ROLE: "Обновить роль",
  UPDATE_ROLE_DESCRIPTION: "Обновить роль для этого участника",
  OWNER: "Владелец",
  GUEST: "Гость",
  MEMBER: "Участник",
  ADMIN: "Администратор",
  SELECT_ROLE: "Выберите роль",
  ROLE: "Роль",
  INVITE_MEMBER_DESCRIPTION:
    "Отправьте приглашение, чтобы добавить нового участника в вашу организацию.",
  MEMBERS_INSTRUCTIONS: "Пригласить новых участников в вашу организацию.",
  MEMBERS_DESCRIPTION: "Добавляйте или удаляйте участников и управляйте их ролями.",
  MEMBERS: "Участники",
  INVITE_MEMBER: "Пригласить участника",
  REMOVE_MEMBER_SUCCESS: "Участник успешно удален",
  REMOVE_MEMBER_CONFIRM: "Вы уверены, что хотите удалить этого участника из организации?",
  REMOVE_MEMBER: "Удалить участника",
  MANAGE_ORGANIZATION: "Управление организацией",
  LEAVE_ORGANIZATION_SUCCESS: "Вы успешно покинули организацию.",
  LEAVE_ORGANIZATION_CONFIRM: "Вы уверены, что хотите покинуть эту организацию?",
  LEAVE_ORGANIZATION: "Покинуть организацию",
  ORGANIZATIONS_INSTRUCTIONS:
    "Создайте организацию для совместной работы с другими пользователями.",
  ORGANIZATIONS_DESCRIPTION: "Управление вашими организациями и членством.",
  ORGANIZATIONS: "Организации",
  USER: "Пользователь",
  BY_CONTINUING_YOU_AGREE: "Продолжая, вы соглашаетесь с",
  PROTECTED_BY_RECAPTCHA: "Этот сайт защищен reCAPTCHA.",
  TERMS_OF_SERVICE: "Условиями обслуживания",
  PRIVACY_POLICY: "Политикой конфиденциальности",
  DELETE_LOGO: "Удалить логотип",
  UPLOAD_LOGO: "Загрузить логотип",
  UPLOAD: "Загрузить",
  LOGO_INSTRUCTIONS: "Логотип необязателен, но настоятельно рекомендуется.",
  LOGO_DESCRIPTION: "Нажмите на логотип, чтобы загрузить собственный из ваших файлов.",
  LOGO: "Логотип",
  UPLOAD_AVATAR: "Загрузить аватар",
  SESSION_NOT_FRESH: "Ваша сессия устарела. Пожалуйста, войдите снова.",
  GO_BACK: "Вернуться назад",
  VERIFY_YOUR_EMAIL_DESCRIPTION:
    "Пожалуйста, подтвердите свой адрес электронной почты. Проверьте свой почтовый ящик на наличие письма с подтверждением. Если вы не получили письмо, нажмите кнопку ниже, чтобы отправить его повторно.",
  VERIFY_YOUR_EMAIL: "Подтвердите свой Email",
  SIGN_IN_USERNAME_PLACEHOLDER: "Имя пользователя или email",
  OPTIONAL_BRACKETS: "(Необязательно)",
  USERNAME_PLACEHOLDER: "Имя пользователя",
  USERNAME_INSTRUCTIONS: "Пожалуйста, используйте максимум 32 символа.",
  USERNAME_DESCRIPTION: "Введите имя пользователя, которое хотите использовать для входа.",
  USERNAME: "Имя пользователя",
  UPDATED_SUCCESSFULLY: "Успешно обновлено",
  UNLINK: "Отвязать",
  SEND_VERIFICATION_CODE: "Отправить проверочный код",
  TWO_FACTOR_TOTP_LABEL: "Отсканируйте QR-код вашим приложением аутентификации",
  TWO_FACTOR_PROMPT: "Двухфакторная аутентификация",
  TWO_FACTOR_DISABLED: "Двухфакторная аутентификация отключена",
  TWO_FACTOR_ENABLED: "Двухфакторная аутентификация была включена",
  TWO_FACTOR_ENABLE_INSTRUCTIONS: "Пожалуйста, введите ваш пароль, чтобы включить 2FA",
  TWO_FACTOR_DISABLE_INSTRUCTIONS: "Пожалуйста, введите ваш пароль, чтобы отключить 2FA.",
  TWO_FACTOR_CARD_DESCRIPTION: "Добавьте дополнительный уровень безопасности вашему аккаунту.",
  TWO_FACTOR_DESCRIPTION: "Пожалуйста, введите ваш одноразовый пароль, чтобы продолжить",
  TWO_FACTOR_ACTION: "Проверить код",
  TWO_FACTOR: "Двухфакторная",
  TRUST_DEVICE: "Доверять этому устройству",
  SWITCH_ACCOUNT: "Переключить аккаунт",
  SECURITY: "Безопасность",
  SAVE: "Сохранить",
  SETTINGS: "Настройки",
  SET_PASSWORD_DESCRIPTION:
    "Нажмите кнопку ниже, чтобы получить письмо для настройки пароля для вашего аккаунта.",
  SET_PASSWORD: "Установить пароль",
  SESSIONS_DESCRIPTION: "Управление вашими активными сессиями и отзыв доступа.",
  SESSIONS: "Сессии",
  SIGN_UP_EMAIL: "Проверьте вашу электронную почту на наличие ссылки для подтверждения.",
  SIGN_UP_DESCRIPTION: "Введите вашу информацию, чтобы создать аккаунт",
  SIGN_UP_ACTION: "Создать аккаунт",
  SIGN_UP: "Регистрация",
  SIGN_OUT: "Выйти",
  SIGN_IN_WITH: "Войти через",
  SIGN_IN_USERNAME_DESCRIPTION:
    "Введите ваше имя пользователя или email ниже, чтобы войти в аккаунт",
  SIGN_IN_DESCRIPTION: "Введите ваш email ниже, чтобы войти в ваш аккаунт",
  SIGN_IN_ACTION: "Войти",
  SIGN_IN: "Войти",
  API_KEY: "API Ключ",
  DELETE_API_KEY_CONFIRM: "Вы уверены, что хотите удалить этот API ключ?",
  DELETE_API_KEY: "Удалить API ключ",
  REVOKE: "Отозвать",
  REQUEST_FAILED: "Запрос не удался",
  RESET_PASSWORD_SUCCESS: "Пароль успешно сброшен",
  RESET_PASSWORD_DESCRIPTION: "Введите ваш новый пароль ниже",
  RESET_PASSWORD_ACTION: "Сохранить новый пароль",
  RESET_PASSWORD: "Сбросить пароль",
  RESEND_VERIFICATION_EMAIL: "Повторно отправить письмо подтверждения",
  RESEND_CODE: "Повторно отправить код",
  REMEMBER_ME: "Запомнить меня",
  RECOVER_ACCOUNT_DESCRIPTION: "Пожалуйста, введите резервный код для доступа к вашему аккаунту",
  RECOVER_ACCOUNT_ACTION: "Восстановить аккаунт",
  RECOVER_ACCOUNT: "Восстановление аккаунта",
  PROVIDERS_DESCRIPTION: "Подключите ваш аккаунт к стороннему сервису.",
  PROVIDERS: "Провайдеры",
  PASSWORDS_DO_NOT_MATCH: "Паролы не совпадают",
  PASSWORD_REQUIRED: "Пароль обязателен",
  PASSWORD_PLACEHOLDER: "Пароль",
  PASSWORD: "Пароль",
  CREATE_ORGANIZATION_SUCCESS: "Организация успешно создана",
  ORGANIZATION_SLUG_PLACEHOLDER: "acme-inc",
  ORGANIZATION_SLUG_INSTRUCTIONS: "Пожалуйста, используйте максимум 48 символов.",
  ORGANIZATION_SLUG_DESCRIPTION: "Это пространство имен URL вашей организации.",
  ORGANIZATION_SLUG: "Слаг URL",
  ORGANIZATION_NAME_INSTRUCTIONS: "Пожалуйста, используйте максимум 32 символа.",
  ORGANIZATION_NAME_DESCRIPTION: "Это видимое название вашей организации.",
  ORGANIZATION_NAME_PLACEHOLDER: "Acme Inc.",
  ORGANIZATION_NAME: "Название",
  ORGANIZATION: "Организация",
  CREATE_ORGANIZATION: "Создать организацию",
  NO_EXPIRATION: "Без срока действия",
  EXPIRES: "Истекает",
  NEVER_EXPIRES: "Никогда не истекает",
  CREATE_API_KEY_SUCCESS:
    "Пожалуйста, скопируйте ваш API ключ и сохраните его в надежном месте. По соображениям безопасности мы не можем показать его снова.",
  API_KEY_CREATED: "API ключ создан",
  API_KEY_NAME_PLACEHOLDER: "Новый API ключ",
  CREATE_API_KEY_DESCRIPTION:
    "Введите уникальное имя для вашего API ключа, чтобы отличать его от других ключей.",
  CREATE_API_KEY: "Создать API ключ",
  API_KEYS_INSTRUCTIONS: "Создавайте API ключи для программного доступа к вашему аккаунту.",
  API_KEYS_DESCRIPTION: "Управление вашими API ключами для безопасного доступа.",
  API_KEYS: "API ключи",
  PERSONAL_ACCOUNT: "Личный аккаунт",
  PASSKEYS_INSTRUCTIONS: "Безопасный доступ к вашему аккаунту без пароля.",
  PASSKEYS_DESCRIPTION: "Управление вашими ключами доступа (passkeys).",
  PASSKEYS: "Ключи доступа (Passkeys)",
  PASSKEY: "Ключ доступа (Passkey)",
  OR_CONTINUE_WITH: "Или продолжить через",
  ONE_TIME_PASSWORD: "Одноразовый пароль",
  NEW_PASSWORD_REQUIRED: "Новый пароль обязателен",
  NEW_PASSWORD_PLACEHOLDER: "Новый пароль",
  NEW_PASSWORD: "Новый пароль",
  NAME_PLACEHOLDER: "Имя",
  NAME_INSTRUCTIONS: "Пожалуйста, используйте максимум 32 символа.",
  NAME_DESCRIPTION: "Пожалуйста, введите ваше полное имя или отображаемое имя.",
  NAME: "Имя",
  EMAIL_OTP_VERIFICATION_SENT: "Пожалуйста, проверьте вашу почту на наличие проверочного кода.",
  EMAIL_OTP_DESCRIPTION: "Введите ваш email, чтобы получить код",
  EMAIL_OTP_VERIFY_ACTION: "Проверить код",
  EMAIL_OTP_SEND_ACTION: "Отправить код",
  EMAIL_OTP: "Код на Email",
  MAGIC_LINK_EMAIL: "Проверьте вашу почту на наличие волшебной ссылки",
  MAGIC_LINK_DESCRIPTION: "Введите ваш email, чтобы получить волшебную ссылку",
  MAGIC_LINK_ACTION: "Отправить волшебную ссылку",
  MAGIC_LINK: "Волшебная ссылка",
  LINK: "Привязать",
  FORGOT_PASSWORD_LINK: "Забыли ваш пароль?",
  FORGOT_PASSWORD_EMAIL: "Проверьте вашу почту на наличие ссылки для сброса пароля.",
  FORGOT_PASSWORD_DESCRIPTION: "Введите ваш email, чтобы сбросить пароль",
  FORGOT_PASSWORD_ACTION: "Отправить ссылку для сброса",
  FORGOT_PASSWORD: "Забыли пароль",
  FORGOT_AUTHENTICATOR: "Забыли аутентификатор?",
  IS_THE_SAME: "такой же",
  IS_REQUIRED: "обязателен",
  IS_INVALID: "недействителен",
  ENABLE_TWO_FACTOR: "Включить двухфакторную аутентификацию",
  EMAIL_VERIFICATION_SUCCESS: "Подтверждение почты прошло успешно.",
  EMAIL_VERIFICATION_DESCRIPTION:
    "Пожалуйста, проверьте вашу почту на наличие проверочного кода для завершения регистрации.",
  EMAIL_VERIFICATION: "Подтверждение Email",
  EMAIL_VERIFY_CHANGE: "Пожалуйста, проверьте вашу почту, чтобы подтвердить изменения.",
  EMAIL_REQUIRED: "Адрес электронной почты обязателен",
  EMAIL_PLACEHOLDER: "m@example.com",
  EMAIL_IS_THE_SAME: "Email совпадает с текущим",
  EMAIL_INSTRUCTIONS: "Пожалуйста, введите действительный адрес электронной почты.",
  EMAIL_DESCRIPTION: "Введите адрес электронной почты, который вы хотите использовать для входа.",
  EMAIL: "Email",
  DONE: "Готово",
  DONT_HAVE_AN_ACCOUNT: "Нет аккаунта?",
  DISABLED_CREDENTIALS_DESCRIPTION: "Выберите провайдера, чтобы войти в ваш аккаунт",
  DISABLE_TWO_FACTOR: "Отключить двухфакторную аутентификацию",
  DELETE_ACCOUNT_SUCCESS: "Ваш аккаунт был удален.",
  DELETE_ACCOUNT_VERIFY:
    "Пожалуйста, проверьте вашу почту, чтобы подтвердить удаление вашего аккаунта.",
  DELETE_ACCOUNT_INSTRUCTIONS:
    "Пожалуйста, подтвердите удаление вашего аккаунта. Это действие необратимо, поэтому действуйте с осторожностью.",
  DELETE_ACCOUNT_DESCRIPTION:
    "Навсегда удалить ваш аккаунт и все его содержимое. Это действие необратимо, поэтому действуйте с осторожностью.",
  DELETE_ACCOUNT: "Удалить аккаунт",
  DELETE_AVATAR: "Удалить аватар",
  DELETE: "Удалить",
  UPDATE: "Обновить",
  CURRENT_SESSION: "Текущая сессия",
  CURRENT_PASSWORD_PLACEHOLDER: "Текущий пароль",
  CURRENT_PASSWORD: "Текущий пароль",
  CONTINUE: "Продолжить",
  COPY_ALL_CODES: "Скопировать все коды",
  COPY_TO_CLIPBOARD: "Скопировать в буфер обмена",
  COPIED_TO_CLIPBOARD: "Скопировано в буфер обмена",
  CONTINUE_WITH_AUTHENTICATOR: "Продолжить с аутентификатором",
  CONFIRM_PASSWORD_REQUIRED: "Подтверждение пароля обязательно",
  CONFIRM_PASSWORD_PLACEHOLDER: "Подтвердите пароль",
  CONFIRM_PASSWORD: "Подтвердите пароль",
  CHANGE_PASSWORD_SUCCESS: "Ваш пароль был изменен.",
  CHANGE_PASSWORD_INSTRUCTIONS: "Пожалуйста, используйте минимум 8 символов.",
  CHANGE_PASSWORD_DESCRIPTION: "Введите ваш текущий пароль и новый пароль.",
  CHANGE_PASSWORD: "Изменить пароль",
  CANCEL: "Отмена",
  BACKUP_CODE: "Резервный код",
  BACKUP_CODE_PLACEHOLDER: "Резервный код.",
  BACKUP_CODES_DESCRIPTION:
    "Сохраните эти резервные коды в надежном месте. Вы можете использовать их для доступа к вашему аккаунту, если потеряете метод двухфакторной аутентификации.",
  BACKUP_CODES: "Резервные коды",
  BACKUP_CODE_REQUIRED: "Резервный код обязателен",
  AVATAR_INSTRUCTIONS: "Аватар необязателен, но настоятельно рекомендуется.",
  AVATAR_DESCRIPTION: "Нажмите на аватар, чтобы загрузить собственный из ваших файлов.",
  AVATAR: "Аватар",
  ALREADY_HAVE_AN_ACCOUNT: "Уже есть аккаунт?",
  ADD_PASSKEY: "Добавить ключ доступа (Passkey)",
  ADD_ACCOUNT: "Добавить аккаунт",
  ACCOUNTS_INSTRUCTIONS: "Войдите в дополнительный аккаунт.",
  ACCOUNTS_DESCRIPTION: "Управление вашими текущими активными аккаунтами.",
  ACCOUNTS: "Аккаунты",
  ACCOUNT: "Аккаунт",
  APP: "Приложение",
  USER_ALREADY_HAS_PASSWORD: "У пользователя уже есть пароль",
  ACCOUNT_NOT_FOUND: "Аккаунт не найден",
  FAILED_TO_UNLINK_LAST_ACCOUNT: "Не удалось отвязать последний аккаунт",
  SESSION_EXPIRED: "Сессия истекла",
  CREDENTIAL_ACCOUNT_NOT_FOUND: "Учетная запись не найдена",
  EMAIL_CAN_NOT_BE_UPDATED: "Email не может быть обновлен",
  PASSWORD_TOO_LONG: "Пароль слишком длинный",
  PASSWORD_TOO_SHORT: "Пароль слишком короткий",
  USER_EMAIL_NOT_FOUND: "Email пользователя не найден",
  FAILED_TO_GET_USER_INFO: "Не удалось получить информацию о пользователе",
  ID_TOKEN_NOT_SUPPORTED: "ID токен не поддерживается",
  INVALID_TOKEN: "Недействительный токен",
  PROVIDER_NOT_FOUND: "Провайдер не найден",
  SOCIAL_ACCOUNT_ALREADY_LINKED: "Социальный аккаунт уже привязан",
  INVALID_EMAIL_OR_PASSWORD: "Неверный email или пароль",
  INVALID_PASSWORD: "Неверный пароль",
  FAILED_TO_GET_SESSION: "Не удалось получить сессию",
  FAILED_TO_UPDATE_USER: "Не удалось обновить пользователя",
  FAILED_TO_CREATE_SESSION: "Не удалось создать сессию",
  BANNED_USER: "Пользователь забанен",
  YOU_ARE_NOT_ALLOWED_TO_SET_USERS_PASSWORD: "Вам не разрешено устанавливать пароль пользователя",
  YOU_ARE_NOT_ALLOWED_TO_DELETE_USERS: "Вам не разрешено удалять пользователей",
  YOU_ARE_NOT_ALLOWED_TO_REVOKE_USERS_SESSIONS: "Вам не разрешено отзывать сессии пользователей",
  YOU_ARE_NOT_ALLOWED_TO_IMPERSONATE_USERS:
    "Вам не разрешено выдавать себя за других пользователей",
  YOU_ARE_NOT_ALLOWED_TO_BAN_USERS: "Вам не разрешено банить пользователей",
  YOU_ARE_NOT_ALLOWED_TO_LIST_USERS_SESSIONS: "Вам не разрешено просматривать сессии пользователей",
  YOU_ARE_NOT_ALLOWED_TO_LIST_USERS: "Вам не разрешено просматривать список пользователей",
  YOU_ARE_NOT_ALLOWED_TO_CREATE_USERS: "Вам не разрешено создавать пользователей",
  YOU_ARE_NOT_ALLOWED_TO_CHANGE_USERS_ROLE: "Вам не разрешено менять роль пользователей",
  YOU_CANNOT_BAN_YOURSELF: "Вы не можете забанить самого себя",
  USER_ALREADY_EXISTS: "Пользователь уже существует",
  ANONYMOUS_USERS_CANNOT_SIGN_IN_AGAIN_ANONYMOUSLY:
    "Анонимные пользователи не могут снова войти анонимно",
  COULD_NOT_CREATE_SESSION: "Не удалось создать сессию",
  FAILED_TO_CREATE_USER: "Не удалось создать пользователя",
  SERVER_ONLY_PROPERTY: "Свойство только для сервера",
  INVALID_API_KEY_GETTER_RETURN_TYPE: "Неверный тип возврата геттера API ключа",
  INVALID_USER_ID_FROM_API_KEY: "Неверный ID пользователя из API ключа",
  INVALID_API_KEY: "Недействительный API ключ",
  KEY_DISABLED_EXPIRATION: "У ключа отключен срок действия",
  NO_VALUES_TO_UPDATE: "Нет значений для обновления",
  RATE_LIMIT_EXCEEDED: "Превышен лимит запросов",
  METADATA_DISABLED: "Метаданные отключены",
  INVALID_NAME_LENGTH: "Неверная длина имени",
  INVALID_PREFIX_LENGTH: "Неверная длина префикса",
  INVALID_REMAINING: "Неверное оставшееся количество",
  EXPIRES_IN_IS_TOO_LARGE: "Срок действия слишком велик",
  EXPIRES_IN_IS_TOO_SMALL: "Срок действия слишком мал",
  KEY_NOT_RECOVERABLE: "Ключ не подлежит восстановлению",
  USAGE_EXCEEDED: "Использование превышено",
  KEY_EXPIRED: "Ключ истек",
  KEY_DISABLED: "Ключ отключен",
  KEY_NOT_FOUND: "Ключ не найден",
  UNAUTHORIZED_SESSION: "Неавторизованная сессия",
  USER_BANNED: "Пользователь забанен",
  REFILL_INTERVAL_AND_AMOUNT_REQUIRED: "Требуется интервал пополнения и количество",
  REFILL_AMOUNT_AND_INTERVAL_REQUIRED: "Требуется количество пополнения и интервал",
  INVALID_METADATA_TYPE: "Неверный тип метаданных",
  UNKNOWN_ERROR: "Неизвестная ошибка",
  MISSING_RESPONSE: "Отсутствует ответ",
  VERIFICATION_FAILED: "Проверка не удалась",
  SERVICE_UNAVAILABLE: "Сервис недоступен",
  MISSING_SECRET_KEY: "Отсутствует секретный ключ",
  TOO_MANY_ATTEMPTS: "Слишком много попыток",
  USER_NOT_FOUND: "Пользователь не найден",
  INVALID_EMAIL: "Недействительный email",
  INVALID_OAUTH_CONFIGURATION: "Неверная конфигурация OAuth",
  PASSWORD_COMPROMISED: "Пароль скомпрометирован",
  INVALID_SESSION_TOKEN: "Недействительный токен сессии",
  INVITATION_LIMIT_REACHED: "Превышен лимит приглашений",
  YOU_ARE_NOT_ALLOWED_TO_DELETE_THIS_TEAM: "Вам не разрешено удалять эту команду",
  YOU_ARE_NOT_ALLOWED_TO_UPDATE_THIS_TEAM: "Вам не разрешено обновлять эту команду",
  YOU_ARE_NOT_ALLOWED_TO_DELETE_TEAMS_IN_THIS_ORGANIZATION:
    "Вам не разрешено удалять команды в этой организации",
  YOU_ARE_NOT_ALLOWED_TO_CREATE_TEAMS_IN_THIS_ORGANIZATION:
    "Вам не разрешено создавать команды в этой организации",
  ORGANIZATION_MEMBERSHIP_LIMIT_REACHED: "Достигнут лимит членства в организации",
  YOU_ARE_NOT_ALLOWED_TO_UPDATE_THIS_MEMBER: "Вам не разрешено обновлять этого участника",
  UNABLE_TO_REMOVE_LAST_TEAM: "Невозможно удалить последнюю команду",
  YOU_HAVE_REACHED_THE_MAXIMUM_NUMBER_OF_TEAMS: "Вы достигли максимального количества команд",
  FAILED_TO_RETRIEVE_INVITATION: "Не удалось получить приглашение",
  YOU_ARE_NOT_ALLOWED_TO_INVITE_USER_WITH_THIS_ROLE:
    "Вам не разрешено приглашать пользователя с этой ролью",
  INVITER_IS_NO_LONGER_A_MEMBER_OF_THE_ORGANIZATION:
    "Пригласивший больше не является участником организации",
  YOU_ARE_NOT_ALLOWED_TO_CANCEL_THIS_INVITATION: "Вам не разрешено отменять это приглашение",
  YOU_ARE_NOT_THE_RECIPIENT_OF_THE_INVITATION: "Вы не являетесь получателем приглашения",
  INVITATION_NOT_FOUND: "Приглашение не найдено",
  USER_IS_ALREADY_INVITED_TO_THIS_ORGANIZATION: "Пользователь уже приглашен в эту организацию",
  YOU_ARE_NOT_ALLOWED_TO_INVITE_USERS_TO_THIS_ORGANIZATION:
    "Вам не разрешено приглашать пользователей в эту организацию",
  YOU_ARE_NOT_ALLOWED_TO_DELETE_THIS_MEMBER: "Вам не разрешено удалять этого участника",
  YOU_CANNOT_LEAVE_THE_ORGANIZATION_AS_THE_ONLY_OWNER:
    "Вы не можете покинуть организацию, являясь единственным владельцем",
  TEAM_ALREADY_EXISTS: "Команда уже существует",
  YOU_ARE_NOT_ALLOWED_TO_CREATE_A_NEW_TEAM: "Вам не разрешено создавать новую команду",
  ROLE_NOT_FOUND: "Роль не найдена",
  MEMBER_NOT_FOUND: "Участник не найден",
  USER_IS_ALREADY_A_MEMBER_OF_THIS_ORGANIZATION:
    "Пользователь уже является участником этой организации",
  NO_ACTIVE_ORGANIZATION: "Нет активной организации",
  YOU_ARE_NOT_ALLOWED_TO_DELETE_THIS_ORGANIZATION: "Вам не разрешено удалять эту организацию",
  YOU_ARE_NOT_ALLOWED_TO_UPDATE_THIS_ORGANIZATION: "Вам не разрешено обновлять эту организацию",
  USER_IS_NOT_A_MEMBER_OF_THE_ORGANIZATION: "Пользователь не является участником организации",
  ORGANIZATION_NOT_FOUND: "Организация не найдена",
  ORGANIZATION_ALREADY_EXISTS: "Организация уже существует",
  YOU_HAVE_REACHED_THE_MAXIMUM_NUMBER_OF_ORGANIZATIONS:
    "Вы достигли максимального количества организаций",
  YOU_ARE_NOT_ALLOWED_TO_CREATE_A_NEW_ORGANIZATION: "Вам не разрешено создавать новую организацию",
  FAILED_TO_UPDATE_PASSKEY: "Не удалось обновить ключ доступа",
  UNABLE_TO_CREATE_SESSION: "Невозможно создать сессию",
  AUTHENTICATION_FAILED: "Аутентификация не удалась",
  PASSKEY_NOT_FOUND: "Ключ доступа не найден",
  FAILED_TO_VERIFY_REGISTRATION: "Не удалось подтвердить регистрацию",
  YOU_ARE_NOT_ALLOWED_TO_REGISTER_THIS_PASSKEY: "Вам не разрешено регистрировать этот ключ доступа",
  CHALLENGE_NOT_FOUND: "Вызов не найден",
  PHONE_NUMBER_NOT_VERIFIED: "Номер телефона не подтвержден",
  INVALID_OTP: "Неверный одноразовый пароль",
  OTP_EXPIRED: "Одноразовый пароль истек",
  OTP_NOT_FOUND: "Одноразовый пароль не найден",
  INVALID_PHONE_NUMBER_OR_PASSWORD: "Неверный номер телефона или пароль",
  PHONE_NUMBER_EXIST: "Номер телефона существует",
  INVALID_PHONE_NUMBER: "Неверный номер телефона",
  SUBSCRIPTION_NOT_SCHEDULED_FOR_CANCELLATION: "Отмена подписки не запланирована",
  SUBSCRIPTION_NOT_ACTIVE: "Подписка не активна",
  EMAIL_VERIFICATION_REQUIRED: "Требуется подтверждение email",
  FAILED_TO_FETCH_PLANS: "Не удалось загрузить тарифные планы",
  UNABLE_TO_CREATE_CUSTOMER: "Невозможно создать клиента",
  ALREADY_SUBSCRIBED_PLAN: "Уже подписан на этот план",
  SUBSCRIPTION_PLAN_NOT_FOUND: "План подписки не найден",
  SUBSCRIPTION_NOT_FOUND: "Подписка не найдена",
  INSUFFICIENT_TEAM_PERMISSIONS: "Недостаточно прав команды",
  ALREADY_TEAM_MEMBER: "Уже является участником команды",
  NOT_ORGANIZATION_MEMBER: "Не является участником организации",
  CANNOT_REMOVE_LAST_TEAM: "Невозможно удалить последнюю команду",
  TEAM_NAME_TOO_LONG: "Имя команды слишком длинное",
  TEAM_MEMBER_NOT_FOUND: "Участник команды не найден",
  TEAM_NOT_FOUND: "Команда не найдена",
  TEAM_MEMBER_LIMIT_REACHED: "Достигнут лимит участников команды",
  TEAM_LIMIT_REACHED: "Достигнут лимит команд",
  INVALID_TWO_FACTOR_COOKIE: "Неверный куки двухфакторной аутентификации",
  TOO_MANY_ATTEMPTS_REQUEST_NEW_CODE: "Слишком много попыток запроса нового кода",
  INVALID_CODE: "Неверный код",
  INVALID_BACKUP_CODE: "Неверный резервный код",
  BACKUP_CODES_NOT_ENABLED: "Резервные коды не включены",
  TWO_FACTOR_NOT_ENABLED: "Двухфакторная аутентификация не включена",
  TOTP_NOT_ENABLED: "TOTP не включен",
  OTP_HAS_EXPIRED: "Одноразовый пароль истек",
  OTP_NOT_ENABLED: "Одноразовый пароль не включен",
  INVALID_USERNAME: "Неверное имя пользователя",
  USERNAME_TOO_LONG: "Имя пользователя слишком длинное",
  USERNAME_TOO_SHORT: "Имя пользователя слишком короткое",
  USERNAME_IS_ALREADY_TAKEN: "Это имя пользователя уже занято",
  UNEXPECTED_ERROR: "Непредвиденная ошибка",
  EMAIL_NOT_VERIFIED: "Email не подтвержден",
  INVALID_USERNAME_OR_PASSWORD: "Неверное имя пользователя или пароль",
}
